### PR TITLE
Fix ATO crashing when output filename exceeds 255 character limit

### LINKED ISSUE #1935: Android Test Orchestrator crashes when test name is too long
### Description

When the test name is too long, ATO crashes.

### Steps to Reproduce

Create a test class with a test name. Lengths of test class and test name added together must be more than 192 characters long.

(sorry about the test name)

```java
// this class name has 29 characters
@RunWith(AndroidJUnit4.class)
@LargeTest
public class CalculatorInstrumentationTest {

    // this method name has 164 characters
    @Test
    public void typeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationrationtypeOperandsAndPerabca() {
        assertThat(true).isEqualTo(true);
    }
}
```

Place it in `androidTest` target and run it with `./gradlew :app:connectedDebugAndroidTest`. 

### Expected Results

Test passes.

### Actual Results

Gradle fails with:

```
> Task :app:connectedDebugAndroidTest
Starting 0 tests on emulator-5554 - 12


> Task :app:connectedDebugAndroidTest FAILED
Test run failed to complete. Instrumentation run failed due to Process crashed.
```

Digging into the logcat reveals:

```
09-20 13:31:14.586  4399  4399 I AndroidTestOrchestrator: AndroidTestOrchestrator has connected to the orchestration service
09-20 13:31:14.587  4399  4399 I AndroidTestOrchestrator: Single test parameter com.example.android.testing.androidtestorchestratorsample.CalculatorInstrumentationTest#typeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationrationtypeOperandsAndPerabca, skipping test collection
09-20 13:31:14.587  4399  4399 D AndroidRuntime: Shutting down VM
09-20 13:31:14.588  4399  4399 E AndroidRuntime: FATAL EXCEPTION: main
09-20 13:31:14.588  4399  4399 E AndroidRuntime: Process: androidx.test.orchestrator, PID: 4399
09-20 13:31:14.588  4399  4399 E AndroidRuntime: java.lang.RuntimeException: Could not open stream for output
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at androidx.test.orchestrator.AndroidTestOrchestrator.getOutputStream(AndroidTestOrchestrator.java:396)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at androidx.test.orchestrator.AndroidTestOrchestrator.executeNextTest(AndroidTestOrchestrator.java:337)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at androidx.test.orchestrator.AndroidTestOrchestrator.runFinished(AndroidTestOrchestrator.java:303)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at androidx.test.orchestrator.AndroidTestOrchestrator.collectTests(AndroidTestOrchestrator.java:262)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at androidx.test.orchestrator.AndroidTestOrchestrator.access$200(AndroidTestOrchestrator.java:122)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at androidx.test.orchestrator.AndroidTestOrchestrator$1.onServiceConnected(AndroidTestOrchestrator.java:242)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-20 13:31:14.588  4399  4399 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Discovering the character limit

Now remove exactly 1 (one) character from the test name, so it'll be 163 characters long. Together with class name, it'll be 29 + 163 = 192 characters long. Run the test again - it passes.

### AndroidX Test and Android OS Versions

Tested on both `androidx.test:orchestrator:1.4.2` and `androidx.test:orchestrator:1.5.0-alpha01`. Same issue occurs.

### Link to a public git repo demonstrating the problem:

I used [the sample Calculator project](https://github.com/android/testing-samples/tree/main/runner/AndroidTestOrchestratorSample) from [`android/testing-samples`](https://github.com/android/testing-samples) repo. You can paste the first URL into [this website](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fandroid%2Ftesting-samples%2Ftree%2F910bd7cb2a983390ab7dbd74e296607408dcc5a8%2Frunner%2FAndroidTestOrchestratorSample) to download the project easily, and then modify one of the files with the contents above.

### PR DESCRIPTION
**Pull request by bartekpacia**
Fixes #1935

### CODE REVIEW

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java [hunk 1]
```diff
@@ -401,7 +403,15 @@ private String getOutputFile() {
     if (null == test) {
       return TEST_COLLECTION_FILENAME;
     } else {
-      return String.format(TEST_RUN_FILENAME, test);
+      // Max filename length is 255 characters, so tests with longer names have to be truncated to prevent crashes.
+      // To prevent collisions, we append a timestamp to the filename.
+      // Every file also has the dot and "txt" appended, so effectively the max length is 255 - 4 = 251 characters.
+
+      String millis = Long.toString(System.currentTimeMillis());
```
Comment (TWiStErRob) [inline runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:410]: Continuing the conversation from https://github.com/android/android-test/issues/1935#issuecomment-1745813824

If you use the timestamp, then every test run will have unique output, which means that it'll be very hard to compare for example two runs, because the filenames are not deterministic and don't match.

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java [hunk 2]
```diff
@@ -401,7 +403,15 @@ private String getOutputFile() {
...
+      String truncatedTest = test.substring(0, Math.min(test.length(), TEST_NAME_MAX_LENGTH - millis.length() - 1));
+      String name = String.format(TEST_RUN_FILENAME, truncatedTest + "_" + millis);
```
Comment (TWiStErRob) [inline runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:412]: probably should only append if the test name was longer than max?

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java (hunk 1 above)
Comment (bartekpacia) [reply runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:410]: agreed, will use hashCode

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java (hunk 2 above)
Comment (bartekpacia) [reply runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:412]: Probably yes - I just wanted to get it working asap :)

will do

**Comment by bartekpacia** [comment]
Here's a test that causes ATO to crash before changes from this PR, and succeeds with changes made in this PR.

<details><summary>CalculatorInstrumentationTest.java</summary>

```java
package com.example.android.testing.androidtestorchestratorsample;

import androidx.test.core.app.ActivityScenario;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.filters.LargeTest;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import static com.google.common.truth.Truth.assertThat;

@RunWith(AndroidJUnit4.class)
@LargeTest
public class CalculatorInstrumentationTest {

    /**
     * Use {@link ActivityScenario} to create and launch of the activity.
     */
    @Before
    public void launchActivity() {
        ActivityScenario.launch(CalculatorActivity.class);
    }

    @Test
    public void typeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationrationtypeOperandsAndPerabcaAAABBB() {
        assertThat(true).isEqualTo(true);
    }

    @Test
    public void typeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationrationtypeOperandsAndPerabcaa() {
        assertThat(true).isEqualTo(true);
    }

    @Test
    public void abc() {
        assertThat(true).isEqualTo(true);
    }
}
```

</details> 

You can paste it in e.g. [the sample Calculator project](https://github.com/android/testing-samples/tree/main/runner/AndroidTestOrchestratorSample) (replace contents of [this file](https://github.com/android/testing-samples/blob/910bd7cb2a983390ab7dbd74e296607408dcc5a8/runner/AndroidTestOrchestratorSample/app/src/androidTest/java/com/example/android/testing/androidtestorchestratorsample/CalculatorInstrumentationTest.java))

**Comment by bartekpacia** [comment]
I ran the `CalculatorInstrumentationTest.java` (see above) a few times, and the filenames generated are stable and look like this:

```
emulator64_arm64:/data/user_de/0/androidx.test.orchestrator/files $ ls -lAh
total 8.0K
-rw-rw---- 1 u0_a146 u0_a146 58 2023-10-04 13:55 com.example.android.testing.androidtestorchestratorsample.CalculatorInstrumentationTest#abc.txt
-rw-rw---- 1 u0_a146 u0_a146 58 2023-10-04 13:55 com.example.android.testing.androidtestorchestratorsample.CalculatorInstrumentationTest#typeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationrationtypeOperandsA7b138cd9.txt
-rw-rw---- 1 u0_a146 u0_a146 58 2023-10-04 13:55 com.example.android.testing.androidtestorchestratorsample.CalculatorInstrumentationTest#typeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationtypeOperandsAndPerformAddOperationrationtypeOperandsA9ea702c9.txt
-rw-rw---- 1 u0_a146 u0_a146 58 2023-10-04 13:55 testCollection.txt
```

thank you @TWiStErRob for suggesting to use `hashCode()` - it's a good idea

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java (hunk 1 above)
Comment (bartekpacia) [reply runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java]: done

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java (hunk 2 above)
Comment (bartekpacia) [reply runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java]: done

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java [hunk 3]
```diff
@@ -401,7 +400,25 @@ private String getOutputFile() {
     if (null == test) {
       return TEST_COLLECTION_FILENAME;
     } else {
-      return String.format(TEST_RUN_FILENAME, test);
+      String testname = test; // Copy it so we don't modify the original.
```
Comment (brettchabot) [inline runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:403]: nit: would it be more technically correct to call this variable 'filename'

Comment (bartekpacia) [reply runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:403]: agreed - changed

**Comment by bartekpacia** [comment]
I see `feedback/copybara` is failing but I don't have access to it. What's wrong @brettchabot?

**Comment by bartekpacia** [comment]
I fixed the formatting, is it OK now?

Regarding the tests – I don't think [AndroidTestOrchestratorTest.java](https://github.com/android/android-test/blob/ad1e9462d121b92fcc48fcd81ff78cd42bce0895/runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java) is the right place to add a test for the changes made in this PR (in its current form). 

Would you be OK with:
- changing `getOutputFile()` to be public
- changing `getOutputFile()` accept the single int `MAX_FILENAME_LENGTH` parameter, to make tests more readable?

Then I could write a few tests for `getOutputFile()`.

Another idea is to add some really long method name [to one of the testing samples](https://github.com/android/testing-samples/blob/910bd7cb2a983390ab7dbd74e296607408dcc5a8/runner/AndroidTestOrchestratorSample/app/src/androidTest/java/com/example/android/testing/androidtestorchestratorsample/CalculatorInstrumentationTest.java).

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java [hunk 4]
```diff
@@ -401,7 +400,27 @@ private String getOutputFile() {
...
-      return String.format(TEST_RUN_FILENAME, test);
+      String filename = test; // Copy it so we don't modify the original.
+
+      // Max filename length is 255 characters, so tests with longer names have to be truncated to
+      // prevent crashes.
+      // To prevent collisions when the filename exceeds the limit, we replace the last characters
+      // with the test name's
+      // hashCode, formatted in hex.
+
+      final String TEST_RUN_FILENAME_SUFFIX = ".txt";
```
Comment (brettchabot) [inline runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:411]: More lint errors:
Name 'TEST_NAME_MAX_LENGTH' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalFinalVariableName]

Comment (bartekpacia) [reply runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java]: I fixed names of these 3 vars.

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java [hunk 5]
```diff
@@ -401,7 +400,27 @@ private String getOutputFile() {
...
+
+      final String testRunFilenameSuffix = ".txt";
+      final int maxFilenameLength = 255;
+      final int testNameMaxLength = maxFilenameLength - testRunFilenameSuffix.length();
+
+      if (filename.length() <= testNameMaxLength) {
+        return filename + testRunFilenameSuffix;
+      }
+
+      // Name exceeeds max length, truncate it and append its hashCode.
```
Comment (brettchabot) [inline runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:419]: nit: exceeds

**Comment by dmeng** [comment]
> I fixed the formatting, is it OK now?
> 
> Regarding the tests – I don't think [AndroidTestOrchestratorTest.java](https://github.com/android/android-test/blob/ad1e9462d121b92fcc48fcd81ff78cd42bce0895/runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java) is the right place to add a test for the changes made in this PR (in its current form at least).
> 
> Would you be OK with:
> 
> * changing `getOutputFile()` to be public
> * changing `getOutputFile()` accept the single int `MAX_FILENAME_LENGTH` parameter, to make tests more readable?
> 
> Then I could write a few tests for `getOutputFile()` in `AndroidTestOrchestratorTest.java`.
> 
> Another idea is to add some really long method name [to one of the testing samples](https://github.com/android/testing-samples/blob/910bd7cb2a983390ab7dbd74e296607408dcc5a8/runner/AndroidTestOrchestratorSample/app/src/androidTest/java/com/example/android/testing/androidtestorchestratorsample/CalculatorInstrumentationTest.java). Not sure if it's connected to CI on this repo.

Maybe make getOutputFile() protected and take the filename as an arg. That way we don't modify the class variable within the method

          String filename = test; // Copy it so we don't modify the original.

and it's easier to write a test around it. 

I wouldn't go as far as making the method public, since it's not something that should be called from elsewhere. 

---

Also, can you squash the commits?

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java [hunk 6]
```diff
@@ -401,7 +400,27 @@ private String getOutputFile() {
     if (null == test) {
       return TEST_COLLECTION_FILENAME;
     } else {
-      return String.format(TEST_RUN_FILENAME, test);
+      String filename = test; // Copy it so we don't modify the original.
```
Comment (ralf-at-android) [inline runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:403]: String are immutable in Java, one cannot "modify the original".

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java [hunk 7]
```diff
@@ -401,7 +400,27 @@ private String getOutputFile() {
...
+
+      if (filename.length() <= testNameMaxLength) {
+        return filename + testRunFilenameSuffix;
+      }
+
+      // Name exceeds max length, truncate it and append its hashCode.
+      String testHashCode = String.format("%08x", filename.hashCode());
+      filename = filename.substring(0, testNameMaxLength - testHashCode.length()) + testHashCode;
+
+      return filename + testRunFilenameSuffix;
```
Comment (ralf-at-android) [inline runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:423]: Can we have a test for this entire method in https://github.com/android/android-test/blob/main/runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java ?

**Review by ralf-at-android — CHANGES_REQUESTED** [review]

File: runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java (hunk 6 above)
Comment (dmeng) [reply runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:403]: @ralf-at-android it's a class variable though. So I think the idea is that Bartek wants to do operations without having to worry about accidentally modifying the class variable.

Comment (TWiStErRob) [reply runner/android_test_orchestrator/java/androidx/test/orchestrator/AndroidTestOrchestrator.java:403]: Probably simplest is to take a step back and remove the mutation altogether. Then the filename local can be created few lines later, and there's no comment.

**Comment by bartekpacia** [comment]
I extracted the file-truncating logic to a new static `@VisibleForTesting` method called `makeValidFilename`, and wrote a few tests for it.

**Comment by bartekpacia** [comment]
Hi @brettchabot, politely pinging in case you missed it :)

File: runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java [hunk 8]
```diff
@@ -44,4 +44,32 @@ public void testSingleMethodTest_blankInput() {
     assertThat(AndroidTestOrchestrator.isSingleMethodTest(null), is(false));
     assertThat(AndroidTestOrchestrator.isSingleMethodTest(""), is(false));
   }
+
+  @Test
```
Comment (dmeng) [inline runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java:48]: Make this one two separate tests

File: runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java [hunk 9]
```diff
@@ -44,4 +44,32 @@ public void testSingleMethodTest_blankInput() {
...
+        AndroidTestOrchestrator.makeValidFilename("hello_world_abcd", maxLength),
+        is("hello_world_abcd.txt"));
+  }
+
+  @Test
+  public void testMakeValidFilename_tooLong() {
+      final int maxLength = 20;
+
+      final String testHashCode = String.format("%08x", "hello_world_abcde".hashCode());
+      assertThat(testHashCode, is("889cc989"));
```
Comment (dmeng) [inline runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java:68]: No need for this assert. We're not testing String.format or hashCode() here.

Comment (bartekpacia) [reply runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java:68]: I added it here to make it obvious to the reader what's the hash code of `hello_world_abcde`, so the later assert is more obvious to them.

Comment (dmeng) [reply runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java:68]: A code comment for that above testHashCode is plenty.

Comment (bartekpacia) [reply runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java:68]: Sure, will do!

File: runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java (hunk 8 above)
Comment (bartekpacia) [reply runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java:48]: done

File: runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java (hunk 9 above)
Comment (bartekpacia) [reply runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java]: done

File: runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java [hunk 10]
```diff
@@ -44,4 +44,36 @@ public void testSingleMethodTest_blankInput() {
...
+  @Test
+  public void testMakeValidFilename_tooLong() {
+      final int maxLength = 20;
+
+      // hash code of "hello_world_abcde" is "889cc989"
+
+      assertThat(
+        // len("hello_world_abcde") is 17, with ".txt" appended it exceeds maxLength
+        AndroidTestOrchestrator.makeValidFilename("hello_world_abcde", maxLength),
+        is("hello_wo889cc989.txt"));
```
[the remark this answers is not in the document]
Comment (dmeng) [reply runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java:77]: In the case where we have two filenames where the first `maxLength` characters happen to be the same, it wouldn't hurt to have a test to make sure we don't do something that will collide every time (like if `makeValidFilename` truncated and did nothing else).

File: runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java [hunk 11]
```diff
@@ -64,9 +64,8 @@ public void testMakeValidFilename_notTooLong() {
   public void testMakeValidFilename_tooLong() {
       final int maxLength = 20;
 
-      final String testHashCode = String.format("%08x", "hello_world_abcde".hashCode());
-      assertThat(testHashCode, is("889cc989"));
-      
+      // hash code of "hello_world_abcde" is "889cc989"
```
Comment (dmeng) [inline runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java:72]: nit: I said a comment is enough, but that comment should still be close to where we're using the hashcode.  Best would probably be before the is() line. Something like

```
      assertThat(
        // len("hello_world_abcde") is 17, with ".txt" appended it exceeds maxLength
        AndroidTestOrchestrator.makeValidFilename("hello_world_abcde", maxLength),
        // hash code of "hello_world_abcde" is "889cc989"
        is("hello_wo889cc989.txt"));
```

Comment (bartekpacia) [reply runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java:72]: ah sure, np:)

File: runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (bartekpacia) [reply runner/android_test_orchestrator/javatests/androidx/test/orchestrator/AndroidTestOrchestratorTest.java:87]: Good idea, I added a test for this. Thank you both!

**Comment by dmeng** [comment]
Looks good! Can you squash the commits?

**Comment by bartekpacia** [comment]
done!

**Comment by bartekpacia** [comment]
Thanks y'all for supporting me with this contribution. How long does it usually take for a new release to become available?
